version: '3.8'

services:
  schedule-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: schedule-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    # restart: unless-stopped
    networks:
      - schedule-network

  schedule-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: schedule-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Uncomment the following line if you want to run the frontend after the backend is ready
    # depends_on: 
    #   - schedule-backend
    # restart: unless-stopped
    networks:
      - schedule-network

networks:
  schedule-network:
    driver: bridge
