services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
